name: Build Godot Game

on:
  push:
    branches:
      - master

jobs:
  export:
    name: Export Game
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Godot
      uses: chickensoft-games/setup-godot@v1
      with:
        version: 4.4.1  # Correct key
        include-templates: true  # Correct key

    - name: Export to Web (HTML5)
      run: |
        mkdir -p build/web
        godot --headless --export-release "Web" build/web/index.html

    - name: Export to Windows
      run: |
        mkdir -p build/windows
        godot --headless --export-release "Windows Desktop" build/windows/Game.exe

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: godot-builds
        path: build/

